rootProject.name = "xpc-parent"
include(":continuous-operation")
include(":playback-example")
include(":discovery-example")
include(":xpc")
include(":xpc-examples")
include(":basic-operation")
include(":tests")
project(":continuous-operation").projectDir = file("examples/continuous-operation")
project(":playback-example").projectDir = file("examples/playback")
project(":discovery-example").projectDir = file("examples/discovery")
project(":xpc-examples").projectDir = file("examples")
project(":basic-operation").projectDir = file("examples/basic-operation")
project(":tests").projectDir = file("$rootDir/../TestScripts/Java Tests")
